alias myip="curl http://ipecho.net/plain; echo"
alias aliases="vim ~/src/git/dotfiles/aliases.zsh"
alias c=clear
alias top=htop
alias boost="docker start boost; docker attach boost"
alias ubuntu="docker run -it --rm ubuntu"
alias rwxws="docker run -it --rm rwxrob/workspace"
alias shellcheck='function _sc(){ shellcheck -o all $1; }; _sc'
alias sc='function _sc(){ shellcheck -o all $1; }; _sc'
alias snippets='cd $SNIPPETS'
alias scripts='cd $SCRIPTS'
alias vip='vim -p'
alias sz='source ~/.zshrc'
alias ez='vim ~/.zshrc'
