#!/bin/sh

test ! -n "${SCRIPTS}" && echo "SCRIPTS not set" && exit 1;
test ! -n "${1}" && echo "usage: newx <name>" && exit 1;

path="${SCRIPTS}/${1}"

if test -e "${path}"; then
  echo "${1} already exists. Edit? "
  read -r answer
  case "${answer}" in
    y|yes|yep|yeah|ok|okay) exec vim "${path}" ;;
    *) echo "then use a unique name :P" ;;
  esac
  exit 0
fi

printf "#!/bin/sh\n\n" > "${path}"
chmod +x "${path}" 
exec vim +2 "${path}"
